# Configuração para produção no Netlify
backend:
  name: git-gateway
  branch: main

# URL do teu site
site_url: https://sigmasigma.netlify.app

# Define onde os ficheiros de media serão guardados
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Coleções de conteúdo
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Descrição Curta", name: "description", widget: "string", required: false }
      - { label: "Autor", name: "author", widget: "string", default: "Equipa Medisigma", required: false }
      - { label: "Imagem de Destaque", name: "imagem_destaque", widget: "image", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" } # O corpo do post em Markdown/MDX 